name: ipodd
favicon: null
layout_spectrum: 0.8963159895502031
typography_spectrum: 0.14493069099262357
title: 'BiModal IT '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5188649673946202
  lightness: 0.16669232351705432
  saturation: 0.016443110071122646
  rhythmicContrast: 0.3397764714900404
purpose: []
